### PR TITLE
Make sure retina versions are used for sponsors

### PR DESCRIPTION
**Pull request by kgrz**
- Fixes an issue where the hyperlink with the sponsor link is visible on retina screen especially in mobile view.
- Will use @2x images for sponsors' icons wherever present.

### CODE REVIEW

**Comment by swanandp** [comment]
There are a bunch of conflicts, can you please do a pull rebase from `upstream`? Your repo is a few commits behind.

**Comment by kgrz** [comment]
Hmm. That is weird. Will update it tomorrow.

On Wednesday, December 4, 2013, Swanand Pagnis wrote:

> There are a bunch of conflicts, can you please do a pull rebase from
> upstream? Your repo is a few commits behind.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GardenCityRuby/GCRC2014/pull/88#issuecomment-29739995
> .

## 

Kashyap KMBC

**Comment by kgrz** [comment]
@swanandp Looks good to me :/

**Comment by swanandp** [comment]
ok, let me do a fresh merge.

**Pull request merged**
