### PR TITLE
Updating multunus logo

### PR DESCRIPTION
**Pull request by char-star**

### CODE REVIEW

**Comment by char-star** [comment]
That was so quick ;)

**Comment by swanandp** [comment]
Yup, Quick Gun Murugan used to train under me some times. :D

**Comment by swanandp** [comment]
I think the logo is a little cut-off from the side. Maybe we can reduce the size by 1px overall?

**Comment by char-star** [comment]
Ahh .. got it ... lemme change that. Btw, the css isn't updated? It's just the less file that I should change right?

**Comment by swanandp** [comment]
Right. We have a rake task for updating the css. @gnufied : is it part of
the deployment ?

**Comment by emilsoman** [comment]
@char-star @swanandp  , the CSS file inside `css` directory is for the theme. This is generated from the LESS file that the theme ships with . Ideally these should be left alone. For adding custom css, I'd created a custom CSS file : `assets/css/custom.css` , please go ahead and use that if you need to add custom CSS .

**Pull request merged**
