### PR TITLE
Add sponsors description to the sponsors page

### LINKED ISSUE #41: Sponsors dedicated page
We need a separate page for sponsors with their logo and blurb. The bottom section in the existing sponsors page can also be used. @kgrz

### PR DESCRIPTION
**Pull request by kgrz**
Intended to fix #41

### CODE REVIEW

**Comment by kgrz** [comment]
@char-star The Dropbox link that you've provided me has descriptions only for 1-2 companies. I'm pushing a test commit. Let me know if this is okay.

**Comment by kgrz** [comment]
screen shot 2013-11-13 at 8 47 57 pm

**Comment by kgrz** [comment]
Zoomed out screenshot

**Comment by char-star** [comment]
Looks good. How about moving the description to the right side of the logo? Otherwise the user has to scroll the page a lot when we have around 15 sponsor logos.

**Comment by swanandp** [comment]
Agree with @char-star

**Comment by swanandp** [comment]
I tried my hand at this. Here is a screenshot of side-by-side:

screen shot 2013-11-14 at 12 31 50 pm

**Comment by char-star** [comment]
Can we not wrap the text below the logo? We can have fixed grids for logo (30%) and writeup (70%). I think it looks neat.

**Comment by swanandp** [comment]
Ok, @kgrz do we have any grid anywhere, or do we need to build it?

**Comment by kgrz** [comment]
We don't have a grid. @char-star's idea is the best option.

**Comment by kgrz** [comment]
@char-star @swanandp Made some changes. (Messed up the previous commit and had to force-push.)

**Comment by swanandp** [comment]
@kgrz Do you have access to the GCRC Dropbox ?

**Comment by kgrz** [comment]
@swanandp  Yeah. @char-star sent an invite in the morning. I will go ahead with filling up the rest of the sponsor details if the layout is agreed upon.

**Comment by swanandp** [comment]
30-70? Sure, go ahead please.

**Comment by kgrz** [comment]
@swanandp ^ That should do it.

**Comment by kgrz** [comment]
I'd suggest trying it once.

**Comment by swanandp** [comment]
Looks good, pushing this now.

**Pull request closed without merging**
