### PR TITLE
Add css changes from dcca161 and 399a11b to less

### PR DESCRIPTION
**Pull request by kgrz**
The two commits 399a11b9c2551c7a12ab2327127503d58ab7223d and
dcca161578c3ec318b6968779e1c32a25d08f04b made changes directly to
the style.css file which will get overridden everytime the style.less
file is recompiled. By making changes to the .less file and recompiling
it everytime, this may be avoided.

Install the less gem and run "lessc assets/less/style.less >
assets/css/style.css" after making changes in the less file. Commit
both.

TODO: This should be a rake task.

### CODE REVIEW

**Comment by kgrz** [comment]
Merge this only after deciding on https://github.com/GardenCityRuby/GCRC2014/pull/52

**Comment by kgrz** [comment]
This can be merged safely now.

**Comment by char-star** [comment]
@swanandp @emilsoman  can you merge this please?

**Comment by swanandp** [comment]
Merged, added rake task.

@gnufied , @emilsoman :  We need to run `rake assets:precompile` before deployment

**Pull request closed without merging**
