### PR TITLE
Added blogpost for CognitiveClouds. Please review the post once for me.

### PR DESCRIPTION
**Pull request by swanandp**

### CODE REVIEW

**Comment by swanandp** [comment]
@char-star - Any suggestions on wordings?

**Comment by char-star** [comment]
@swanandp ... http://www.gardencityruby.org/blog/announcing-associate-sponsor-cognitive-clouds/ is breaking.

**Comment by swanandp** [comment]
Yup, just contacted @emilsoman. We're checking what went wrong

**Comment by emilsoman** [comment]
[Fixed](http://www.gardencityruby.org/blog/announcing-associate-sponsor-cognitive-clouds/)

**Pull request merged**
