### PR TITLE
Adding blog post for Multunus

### PR DESCRIPTION
**Pull request by char-star**

### CODE REVIEW

**Comment by prakashmurthy** [comment]
How come none of the sponsors for whom new blogposts were added today have their logo displayed on the main page of the website?

**Comment by swanandp** [comment]
@char-star, @emilsoman & @kgrz are at it

**Comment by kgrz** [comment]
Yeah, will sort this out.

-- 
Kashyap

**Comment by prakashmurthy** [comment]
Cool. Thanks.

**Pull request merged**
