### PR TITLE
add schedule link to busyconf, fix merge issue

### PR DESCRIPTION
**Pull request by leenasn**

### CODE REVIEW

**Comment by leenasn** [comment]
@swanandp Can you merge this ?

**Comment by swanandp** [comment]
I merged this, but it isn't getting reflected on the website. @emilsoman & @gnufied any chance any of you can take care of this?

**Comment by char-star** [comment]
I guess Auto-deployment isn't working.

**Comment by leenasn** [comment]
We should be able to deploy manually for the timebeing rt?

On Mon, Nov 11, 2013 at 11:14 PM, Satish Kumar Perala <
notifications@github.com> wrote:

> I guess Auto-deployment isn't working.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GardenCityRuby/GCRC2014/pull/46#issuecomment-28221984
> .

## 

Leena S N
Head Of Engineering
Multunus Software Pvt. Ltd.
Blog: http://www.multunus.com/ http://www.multunus.com/author/leena/
 http://www.multunus.com/blog/all/continuous-delivery/
Yahoo/GTalk/MSN/Skype: leenasn
Twitter: @leenasn

**Comment by emilsoman** [comment]
@char-star @leenasn I can see [the changes on the site](http://www.gardencityruby.org/blog/schedule-is-ready/) .

**Comment by swanandp** [comment]
That is because @gnufied fixed it yesterday. It _was_ broken before that.

**Comment by emilsoman** [comment]
Figured it from another thread  :)

**Pull request merged**
