### PR TITLE
Permalinks

### LINKED ISSUE #4: Remove .html from titles
You can do that either by URL rewrites, or by replacing postname.html with postname/index.html 

Examples: 
http://www.gardencityruby.org/sponsors.html
http://www.gardencityruby.org/blog.html

### PR DESCRIPTION
**Pull request by ghost**
Changed /blog.html to /blog
Changed /post-name to /blog/post-name

Fixes #4

### CODE REVIEW

**Comment by prakashmurthy** [comment]
Why is this issue kept open for 6 hours now? Can someone verify it and merge it?

**Comment by emilsoman** [comment]
@codepodu , thanks! I will review and merge the PR. Please feel free to commit on the master branch directly going forward .
@prakashmurthy precisely the reason everybody on the team has push access on the repo .

**Comment by prakashmurthy** [comment]
Please make sure everything works fine before pushing the code. Sponsors page & blog page links from the main page are 404-ing after this merge.

**Comment by emilsoman** [comment]
This is because we are using a different config.yml for the deployment script. @codepodu would have added the navigation changes only to `_config.yml`. We're removing `_config.yml` from the git repo and adding it to `.gitignore` . I'll add a step in `README` that should make this clear.

**Comment by prakashmurthy** [comment]
@emilsoman That is not the main issue. The links are failing because there is a .html extension in the links section in the config files. Removing ".html" makes them work fine.

**Comment by ghost** [comment]
Fixed by #10

**Pull request merged**
