### PR TITLE
Remove the + become_sponsor image and add a link

### LINKED ISSUE #73: "+" button to become a sponsor on homepage is repetitive and not so intuitive
Replace with a text link on the top/bottom of the sponsors section ? @swanandp , @kgrz , what do you think ?

### PR DESCRIPTION
**Pull request by kgrz**
Fixes #73

### CODE REVIEW

**Comment by swanandp** [comment]
@kgrz Can you rebase your commit against master ?

**Comment by emilsoman** [comment]
Let me test this locally, give me a moment please .

**Comment by emilsoman** [comment]
@kgrz , please go ahead and merge master on this, looks like there are some conflicts .

**Comment by kgrz** [comment]
Should be okay now.

**Comment by emilsoman** [comment]
Looks much better ! @kgrz , can you change "Become one" to "Be a sponsor" ?

**Comment by swanandp** [comment]
Closed with 4f6416e

**Pull request closed without merging**
