### PR TITLE
add schedule as iframe

### PR DESCRIPTION
**Pull request by leenasn**
@swanand, @Kashyap can someone do a check before accepting th e PR?

### CODE REVIEW

**Comment by swanandp** [comment]
There seems to be some issue with the headers:

On initial load:

screen shot 2013-11-28 at 10 36 31 pm

After clicking on the link:

screen shot 2013-11-28 at 10 36 40 pm

**Comment by kgrz** [comment]
iframes and responsive websites don't work well together :/ Can't we add a simple summary instead? And a link pointing to busyconf site for details? Like we can have the titles of the talk and link point to the busyconf address. Opinions?

**Comment by swanandp** [comment]
Yup, let's keep this page as is, but add a prominent link on the home page to schedule. Goal: When people come to our website, they should be find the schedule in 1 click, no matter where they are.

**Comment by swanandp** [comment]
Closing this in favour of linking directly to BusyConf.

**Pull request closed without merging**
